apiVersion: v1
kind: Service
metadata:
  name: java-service
spec:
  type: LoadBalancer
  selector:
    app: javaweb
  ports:
  - protocol: TCP
    port: 80          # This is the port exposed to the outside world
    targetPort: 8080
